### PR TITLE
When emitting Jribble for a catch clause, use the symbol's name

### LINKED ISSUE #38: Wrong variable names in try..catch statement of jribble output
Following code snippet:

```
  def catchAndPassToLambda {
    try { true } catch { case ex: Exception => val f = () => ex }
  }
```

results in jribble output where variable holding exception is named `ex` but referenced as `ex$2`. See below:

```
member {
  type: Method
  modifiers {
    isPublic: true
  }
  method {
    name: "catchAndPassToLambda"
    returnType {
      type: Void
    }
    body {
      type: Block
      block {
        statement {
          type: Try
          tryStat {
            block {
              type: Block
              block {
              }
            }
            catch {
              tpe {
                pkg: "java.lang"
                name: "Exception"
              }
              param: "ex"
              body {
                type: Block
                block {
                  statement {
                    type: VarDef
                    varDef {
                      tpe {
                        type: Named
                        namedType {
                          pkg: "scala"
                          name: "Function0"
                        }
                      }
                      name: "f"
                      initializer {
                        type: NewObject
                        newObject {
                          clazz {
                            name: "Try$$anonfun$1"
                          }
                          signature {
                            name: "new"
                            owner {
                              name: "Try$$anonfun$1"
                            }
                            paramType {
                              type: Named
                              namedType {
                                name: "Try"
                              }
                            }
                            paramType {
                              type: Named
                              namedType {
                                pkg: "java.lang"
                                name: "Exception"
                              }
                            }
                            returnType {
                              type: Named
                              namedType {
                                name: "Try$$anonfun$1"
                              }
                            }
                          }
                          argument {
                            type: ThisRef
                          }
                          argument {
                            type: VarRef
                            varRef {
                              name: "ex$2"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by gkossakowski**
of the variable rather than the AST's name for it.

Added test-case for problem mentioned in #38.

Fixes #38.

Signed-off-by: Grzegorz Kossakowski grzegorz.kossakowski@gmail.com

### CODE REVIEW

**Comment by gkossakowski** [comment]
To build it should be enough to run `ant clean && ant`. Then run `cd test; ./partest --jribble`.

**Comment by anovstrup** [comment]
I get: 

quick.lib:
    [mkdir] Created dir: /home/aaron/scala-gwt/scala/build/quick/classes/library
    [javac] Compiling 25 source files to /home/aaron/scala-gwt/scala/build/quick/classes/library
    [javac] Compiling 41 source files to /home/aaron/scala-gwt/scala/build/quick/classes/library
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
[scalacfork] Compiling 687 files to /home/aaron/scala-gwt/scala/build/quick/classes/library
[scalacfork] error: scala.reflect.internal.MissingRequirementError: class scala.reflect.BeanInfo not found.
[scalacfork]    at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
[scalacfork]    at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
[scalacfork]    at scala.reflect.internal.Definitions$definitions$$anonfun$getModuleOrClass$3.apply(Definitions.scala:677)
[scalacfork]    at scala.reflect.internal.Definitions$definitions$$anonfun$getModuleOrClass$3.apply(Definitions.scala:677)
[scalacfork]    at scala.reflect.internal.Symbols$Symbol.orElse(Symbols.scala:1748)
[scalacfork]    at scala.reflect.internal.Definitions$definitions$.getModuleOrClass(Definitions.scala:676)
[scalacfork]    at scala.reflect.internal.Definitions$definitions$.getModuleOrClass(Definitions.scala:685)
[scalacfork]    at scala.reflect.internal.Definitions$definitions$.getClass(Definitions.scala:644)
[scalacfork]    at scala.tools.nsc.backend.jvm.GenJVM$BytecodeGenerator.<init>(GenJVM.scala:182)
[scalacfork]    at scala.tools.nsc.backend.jvm.GenJVM$JvmPhase.run(GenJVM.scala:137)
[scalacfork]    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1060)
[scalacfork]    at scala.tools.nsc.Global$Run.compile(Global.scala:1148)
[scalacfork]    at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
[scalacfork]    at scala.tools.nsc.Main$.doCompile(Main.scala:81)
[scalacfork]    at scala.tools.nsc.Driver.process(Driver.scala:52)
[scalacfork]    at scala.tools.nsc.Driver.main(Driver.scala:65)
[scalacfork]    at scala.tools.nsc.Main.main(Main.scala)
[scalacfork] 
[scalacfork] error: fatal error: class scala.reflect.BeanInfo not found.

BUILD FAILED
/home/aaron/scala-gwt/scala/build.xml:497: java.lang.RuntimeException: Compilation failed because of an internal compiler error; see the error output for details.
        at scala.sys.package$.error(package.scala:27)
        at scala.tools.ant.sabbus.ScalacFork.execute(ScalacFork.scala:144)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1397)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1366)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1249)
        at org.apache.tools.ant.Main.runBuild(Main.java:801)
        at org.apache.tools.ant.Main.startAnt(Main.java:218)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

**Comment by gkossakowski** [comment]
Weird. Can you try `ant all.clean && ant`?

**Comment by anovstrup** [comment]
Success, including partest.

**Comment by gkossakowski** [comment]
Ok. I'll go ahead and merge this in. If there's still problem with using compiled binaries to build samples we'll need to track it down on mailing list as that would be something unknown to me.

**Pull request merged**
